---
title: "Trend Strategy"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---

```{r setup, message = FALSE}

library(tidyquant)
library(tidyverse)
library(timetk)
library(broom)
library(tibbletime)
library(highcharter)
library(scales)
library(flexdashboard)

knitr::opts_chunk$set(message=FALSE, warning=FALSE)


```


Sidebar {.sidebar}
=====================================
  
```{r}

textInput("asset", "Asset", "EEM")


dateRangeInput("date", "Period chart",
               start  = "2010-01-01",
               end    = Sys.Date(),
               min    = "1980-01-01",
               max    = Sys.Date(),
               format = "yyyy-mm-dd",
               sep = "-")


actionButton("go", "Submit")
```

```{r}

roll_mean_50 <- 
  rollify(mean, window = 50)

roll_mean_200 <- 
  rollify(mean, window = 200)

prices <- eventReactive(input$go, {
  
  
  tq_get(input$asset, 
         get = "stock.prices",
         from = input$date[1],
         to = input$date[2])
    
})

sma_trend_results <- eventReactive(input$go, {

prices <- prices()

sma_trend_results <- 
  prices %>% 
  select(date, adjusted) %>%
  `colnames<-`(c("date", "asset")) %>% 
  mutate(sma_200 = roll_mean_200(asset),
         sma_50 = roll_mean_50(asset),
         asset_returns = log(asset) - log(lag(asset)))

})

```

Moving Averages
=====================================

Row 1 {.tabset}
---------------------

### SMA 50 v. SMA 200

```{r}
renderHighchart({
  
  sma_hc <- sma_trend_results() %>%
  select(date, sma_200, sma_50, asset) %>% 
  tk_xts(date_var = date) 
  
  highchart(type = "stock") %>% 
  hc_title(text = "SMA 50 v. SMA 200") %>%
  hc_add_series(sma_hc$sma_200, color = "cornflowerblue",  name = "sma200") %>%
  hc_add_series(sma_hc$sma_50, color = "green", name = "sma50") %>%
  hc_add_series(sma_hc$asset, color = "red", name = "price", dashStyle = "DashDot") %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_legend(enabled = TRUE) %>% 
  hc_yAxis(labels = list(format = "${value:,.2f}")) %>% 
  hc_tooltip(pointFormat = "{point.series.name}: ${point.y:.2f}")
  
})
```
  


### Explanation
```{r}
renderText(
  "This Shiny app allows you to choose an asset and a time period and visualize how a dollar would have grown when invested in a portfolio of 90% the chosen asset and 10%  t-bills verus a strategy that buys the asset 100% when the the 50 day moving average of the asset is higher than the 200 day moving average of the asset."
)
```

Row 2 {.tabset}
---------------------



### Asset Returns Stats

```{r}
renderTable({
  returns_xts <- sma_trend_results() %>%
  select(date, asset_returns) %>% 
  tk_xts(date_var = date) 
  
  table.Stats(returns_xts) %>% 
  as_tibble() %>% 
  rownames_to_column()
})
```

### Asset Drawdowns

```{r}
renderTable({
  returns_xts <- sma_trend_results() %>%
  select(date, asset_returns) %>% 
  tk_xts(date_var = date) 
  
  table.Drawdowns(returns_xts) %>% 
  as_tibble() %>% 
  rownames_to_column()
})
```


### Bootstrapped distribution

```{r}
renderPlot({

samples <- 5000

sma_trend_results <- sma_trend_results()

  rerun(.n = samples, 
      sample(sma_trend_results$asset_returns, 
             30, 
             replace = T)) %>%  
  `names<-`(paste("sample", 1:samples, sep = " ")) %>%
  simplify_all() %>% 
  as_tibble() %>% 
  gather(sample, thirty_dailies) %>% 
  group_by(sample) %>% 
  summarise(mean = mean(thirty_dailies)) %>%  
  ungroup() %>% 
  mutate(se = sd(mean),
            upper_ci = mean(mean) + (2 * se),
            lower_ci = mean(mean) - (2 * se)) %>% 
  ggplot(aes(x = mean)) +
  geom_histogram(binwidth = .0001, fill = "pink", color = "cornflowerblue") + 
  geom_segment(aes(x = upper_ci, 
                   xend = upper_ci, 
                   y = 0, 
                   yend = Inf)) +
  geom_segment(aes(x = lower_ci, 
                   xend = lower_ci, 
                   y = 0, 
                   yend = Inf))
})
```
